# Generated by Django 4.1.7 on 2023-04-13 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart', '0005_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pro_image',
            field=models.ImageField(upload_to='product/'),
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile', models.BigIntegerField(blank=True, default=0, null=True)),
                ('price', models.BigIntegerField(blank=True, default=0, null=True)),
                ('quantity', models.BigIntegerField(blank=True, default=0, null=True)),
                ('status', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flipkart.registration')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flipkart.product')),
            ],
        ),
    ]
